name: OAS to Kong

on:
  push:
    branches:
      - main

jobs:

#  this job is useful to debug workflows, see https://github.com/mheap/debug-artifact
#  debug-artifacts:
#    name: Upload Debug Artifacts
#    runs-on: ubuntu-latest
#    steps:
#      - name: Upload Debug Artifacts
#        uses: mheap/debug-artifact@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  has-changes:
    name: Have OAS or pipeline files changed
    runs-on: ubuntu-latest

    outputs:
      are-changes: ${{ steps.changed-files.outputs.files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changed-files
        with:
          filters: |
            files:
              - 'flight-data/flights/openapi.yaml'
              - 'flight-data/flights/kong/patches.yaml'
              - 'flight-data/routes/openapi.yaml'
              - 'flight-data/routes/kong/patches.yaml'
              - 'sales/bookings/opeanapi.yaml'
              - 'sales/bookings/kong/patches.yaml'
              - '.github/workflows/oas-to-kong.yaml'

  oas-to-kong:
    name: Convert OAS to Kong configurations

    needs: has-changes
    if: ${{ needs.has-changes.outputs.are-changes == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup kced 
        uses: rspurgeon/setup-kced@v1
        with:
          kced-version: '0.1.11'
          wrapper: false

      - name: Convert Flights API to Kong
        # In two steps, convert the OpenAPI Spec to a Kong declarative configuration 
        #   and then patch the result with the data in the kong/patches.yaml 
        run: |
          kced openapi2kong -s flight-data/flights/openapi.yaml | kced patch -o .github/artifacts/kong/flight-data-flights-kong.yaml flight-data/flights/kong/patches.yaml

      - name: Convert Routes API to Kong
        # In two steps, convert the OpenAPI Spec to a Kong declarative configuration 
        #   and then patch the result with the data in the kong/patches.yaml 
        run: |
          kced openapi2kong -s flight-data/routes/openapi.yaml | kced patch -o .github/artifacts/kong/flight-data-routes-kong.yaml flight-data/flights/kong/patches.yaml

      - name: Convert Bookings API to Kong
        # In two steps, convert the OpenAPI Spec to a Kong declarative configuration 
        #   and then patch the result with the data in the kong/patches.yaml 
        run: |
          kced openapi2kong -s sales/bookings/openapi.yaml | kced patch -o .github/artifacts/kong/sales-bookings-kong.yaml 'sales/bookings/kong/patches.yaml'

      - name: Combine Kong Configurations
        id: kong-combine
        run: |
          kced merge .github/artifacts/kong/*-kong.yaml -o platform/kong-combined.yaml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kong-configurations
          path: .github/artifacts/kong/*.yaml

      - name: Create PR for changed Kong Gateway Configuration
        uses: peter-evans/create-pull-request@v5
        with:
          title: Kong Gateway combined configuration change 