name: OAS to Kong

on:
  push:
    branches:
      - main
      - actions

jobs:
  changes:
    name: Get Changed Spec Files
    runs-on: ubuntu-latest

    outputs:
      changed-specs: ${{ steps.changed-specs.outputs.spec }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changed-specs 
        with:
          filters: |
            spec:
              - 'flight-data/flights/openapi.yaml'
              - 'flight-data/routes/openapi.yaml'
              - 'sales/bookings/opeanapi.yaml'
